# Generated by Django 4.2.4 on 2023-09-05 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="places", new_name="Place",),
    ]
