# Generated by Django 4.2.4 on 2023-09-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_places_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("img", models.ImageField(upload_to="img")),
                ("desc", models.TextField()),
            ],
        ),
    ]
